version: "2"
services:
  zookeeper:
    image: zookeeper
    container_name: zoozoo
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    ports:
      - 8083:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    # volumes:
    #   - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml
  
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  redisinsight:
    image: redislabs/redisinsight
    container_name: redis-ui
    restart: always
    depends_on:
      - "redis"
    ports:
      - 8001:8001

  db:
    image: mongo
    container_name: mongoDB
    ports:
      - "27017:27017"
    # command: sh /db/migrateData.sh
    # volumes:
    #   - /dbMigration:/dbMigration
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root

  migrator:
    ## this service will start and migrate data and then stop
    build:
      context: ./dbMigration
      dockerfile: Dockerfile
    container_name: dataMigration

  mongo-express:
    container_name: mongo-express
    restart: always
    links:
      - 'db:mongo'
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongoDB:27017
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: root
    image: mongo-express
    depends_on:
      - db