###

curl -X 'POST' \
  'http://localhost:2020/v1/kafka/postMessage' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "config" : {
    "topic" : "test",
    "key" : "key1"
  },
  "data" : {"test" : "12312313"}
}'
###
 