
###

curl -X 'GET' \
  'http://localhost:2020/users' \
  -H 'accept: application/json'

###

curl -X 'GET' \
  'http://localhost:2020/users/1' \
  -H 'accept: application/json'


###

curl -X 'POST' \
  'http://localhost:2020/users' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "id": 2,
  "name": "string",
  "email": "user@example.com",
  "age": 0
}'

###

curl -X 'DELETE' \
  'http://localhost:2020/users/1' \
  -H 'accept: application/json'


###

curl -X 'DELETE' \
  'http://localhost:2020/users/all' \
  -H 'accept: application/json'
