import dotenv from 'dotenv';
import { bool, cleanEnv, host, num, port, str, testOnly, url } from 'envalid';

dotenv.config();

export const env = cleanEnv(process.env, {
 NODE_ENV: str({ devDefault: testOnly('test'), choices: ['development', 'production', 'test'] }),
 HOST: host({ devDefault: testOnly('localhost') }),
 PORT: port({ devDefault: testOnly(3000) }),
 CORS_ORIGIN: str({ devDefault: testOnly('http://localhost:2020') }),
 COMMON_RATE_LIMIT_MAX_REQUESTS: num({ devDefault: testOnly(1000) }),
 COMMON_RATE_LIMIT_WINDOW_MS: num({ devDefault: testOnly(1000) }),
 REDIS_HOST: str(),
 REDIS_PORT: num(),
 KAFKA_BROKER: str(),
 CLIENT_ID: str(),
 ENV: str(),
 PRODUCTS_API: url(),
 MONGO_URI_LOCAL: str(),
 MONGO_URI_TESTS_LOCAL: str(),
 MONGO_URI: str(),
 MONGO_URI_TESTS: str(),
 SLACK_TOKEN: str(),
 ENABLE_SLACK_LOGGING: bool({ default: false }),
 SLACK_CHANNEL: str(),
 BASE_URL: str({ devDefault: testOnly('http://localhost:2020') }),
 API_VERSION: str(),
 OPENAI_API_KEY: str(),
 VISION_BASE_URL: url({
     default: 'https://openrouter.ai/api/v1',
     desc: 'Base URL for the image analysis (vision) OpenAI-compatible provider',
    }),
    VISION_API_KEY: str({ default: '', desc: 'API key for the vision provider (falls back to OPENAI_API_KEY)' }),
    ENABLE_FILE_LOGGING: bool({ default: false }),
    AI_MODELS: str({ default: 'ai/gemma3', desc: 'Comma-separated list of AI models' }),
 LOCALAI_EMBDED_MODEL: str({ default: 'nemotron-3-embed-1b-q4', desc: 'Embedding model' }),
 LOCALAI_SUMMARY_MODEL: str({ default: 'lfm2.5-1.2b-instruct', desc: 'Summary model' }),
 LOCALAI_RELEVANCE_MODEL: str({ default: 'lfm2.5-1.2b-instruct', desc: 'History check model' }),
 LOCALAI_IMAGE_ANALYSIS_MODEL: str({ default: 'gemma-4-26b-a4b-it-apex-i-quality', desc: 'Image analysis model' }),
 OPENROUTER_BASE_URL: url({ default: 'https://openrouter.ai/api/v1', desc: 'Base URL for the OpenRouter API' }),
 OPENROUTER_API_KEY: str({ default: '', desc: 'API key for the OpenRouter API' }),
 OPENROUTER_VISION_MODEL: str({ default: 'google/gemma-4-26b-a4b-it:free', desc: 'Image analysis model' }),
 LOCALAI_CHAT_MODEL: str({ default: 'ai/gemma3', desc: 'Default chat/completions model for LocalAI' }),
 OPENROUTER_CHAT_MODEL: str({ default: 'google/gemma-4-26b-a4b-it:free', desc: 'Default chat/completions model for OpenRouter' }),
 CHROMA_URL: url({ default: 'http://localhost:8000', desc: 'Base URL for the ChromaDB vector store' }),
 RAG_COLLECTION_NAME: str({ default: 'knowledge_base2', desc: 'ChromaDB collection used by the RAG system' }),
 RAG_ENABLED: bool({ default: false, desc: 'Master switch for RAG retrieval in chat' }),
 RAG_TOP_K: num({ default: 3, desc: 'Number of chunks retrieved per query' }),
 LOCALAI_EMBEDDING_MODEL: str({ default: 'nemotron-3-embed-1b-q4', desc: 'Embedding model (canonical name)' }),
 LOCALAI_URL: str({ default: 'http://localhost:8000/v1', desc: 'URL for the LocalAI API' }),
 OLLAMA_URL: str({ default: 'http://localhost:11434', desc: 'Base URL for the Ollama OpenAI-compatible API' }),
 OLLAMA_CHAT_MODEL: str({ default: 'qwen2.5:0.5b', desc: 'Default chat/completions model for Ollama' }),
 ENABLE_REDIS: bool({ default: false, desc: 'Enable Redis' }),
 ENABLE_MINIO: bool({ default: false, desc: 'Enable MinIO' }),
 YOUTUBE_API_KEY: str({ default: '', desc: 'API key for the YouTube Data API v3 (goal-tracker course search)' }),
 GOOGLE_CLIENT_ID: str({ default: '', desc: 'OAuth2 client ID for Google Sign-In / Drive access' }),
 GOOGLE_CLIENT_SECRET: str({ default: '', desc: 'OAuth2 client secret for Google Sign-In / Drive access' }),
 GOOGLE_REDIRECT_URI: str({
  devDefault: testOnly('http://localhost:2020/v1/auth/google/callback'),
  desc: 'OAuth2 redirect URI registered in the Google Cloud console',
 }),
 GOOGLE_DRIVE_SCOPES: str({
  default: 'openid email profile https://www.googleapis.com/auth/drive',
  desc: 'Space-separated OAuth scopes requested on Google sign-in',
 }),
 TOKEN_ENCRYPTION_KEY: str({
  devDefault: testOnly('MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY='),
  desc: '32-byte base64 key used to encrypt stored Google OAuth tokens at rest',
 }),
 SESSION_SECRET: str({ devDefault: testOnly('dev-session-secret'), desc: 'Secret used to sign the session cookie' }),
});
